packages:
  - packages/*
  - scripts/generate-docs-index
  - tools/template-manager

strictPeerDependencies: true
linkWorkspacePackages: true
preferWorkspacePackages: true
minimumReleaseAge: 0

overrides:
  react-json-view-lite: "^2.3.0"
  tmp: "^0.2.6"
  "swagger-jsdoc>js-yaml": "^3.15.2"
  serialize-javascript: "^7.0.5"

allowBuilds:
  esbuild: true
  sharp: true
  storage-engine: true
  "@scarf/scarf": false
  core-js: false
