packages:
  - packages/*
  - scripts/generate-docs-index
catalog:
  "@babel/cli": ^7.26.4
  "@babel/core": ^7.26.9
  "@babel/node": ^7.26.0
  "@babel/plugin-proposal-object-rest-spread": ^7.20.7
  "@babel/plugin-transform-runtime": ^7.26.9
  "@babel/preset-env": ^7.26.9
  "@babel/preset-react": ^7.26.3
  "@babel/preset-typescript": ^7.26.0
  "@babel/register": ^7.25.9
  "@babel/runtime": ^7.26.9
  "@changesets/cli": ^2.28.1
  "@docusaurus/core": ^3.7.0
  "@docusaurus/preset-classic": ^3.7.0
  "@docusaurus/theme-mermaid": ^3.7.0
  "@fastify/express": ^3.0.0
  "@fastify/swagger": ^8.15.0
  "@fastify/swagger-ui": ^4.2.0
  "@godaddy/dmd": ^1.0.4
  "@godaddy/terminus": ^4.12.1
  "@jest/globals": ^29.7.0
  "@svgr/core": ^6.5.1
  "@swc/cli": ^0.3.14
  "@swc/core": ^1.10.18
  "@testing-library/jest-dom": ^5.17.0
  "@testing-library/react": ^13.4.0
  "@types/compression": ^1.7.5
  "@types/concat-stream": ^2.0.3
  "@types/cookie-parser": ^1.4.8
  "@types/cross-spawn": ^6.0.6
  "@types/express": ^4.17.21
  "@types/http-proxy": ^1.17.16
  "@types/inquirer": ^9.0.7
  "@types/jest": ^29.5.14
  "@types/lru-cache": ^5.1.1
  "@types/mocha": ^10.0.10
  "@types/morgan": ^1.9.9
  "@types/node": ^20.17.19
  "@types/react": ^18.3.18
  "@types/uglify-js": ^3.17.5
  "@types/webpack-bundle-analyzer": ^4.7.0
  "@types/workbox-build": ^5.1.0
  "@typescript-eslint/eslint-plugin": ^6.21.0
  "@typescript-eslint/parser": ^6.21.0
  abort-controller: ^3.0.0
  acorn: ^8.14.0
  ajv: ^8.17.1
  babel-core: 7.0.0-bridge.0
  babel-eslint: ^10.1.0
  babel-jest: ^29.7.0
  babel-plugin-add-module-exports: ^1.0.4
  chalk: ^4.1.2
  commander: ^12.1.0
  compression: ^1.8.0
  concat-stream: ^2.0.0
  concurrently: ^9.1.2
  cookie-parser: ^1.4.7
  core-js: ^3.40.0
  create-servers: ^3.3.0
  cross-env: ^7.0.3
  cypress: ^13.17.0
  debug: ^4.4.0
  deepmerge: ^4.3.1
  diagnostics: ^2.0.2
  dotenv: ^16.4.7
  elastic-apm-node: ^4.11.0
  errs: ^0.3.2
  escape-string-regexp: ^1.0.5
  eslint: ^8.57.1
  eslint-config-godaddy: ^7.1.1
  eslint-config-godaddy-react: ^9.1.0
  eslint-config-godaddy-react-typescript: ^4.0.3
  eslint-config-godaddy-typescript: ^4.0.3
  eslint-config-next: ^13.5.8
  eslint-plugin-jest: ^28.11.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.4
  eslint-plugin-unicorn: ^55.0.0
  express: ^4.21.2
  fastify: ^4.29.0
  fs-extra: ^10.1.0
  glob: ^8.1.0
  global-jsdom: ^8.8.0
  handlebars: ^4.7.8
  happy-feet: ^2.2.0
  hoist-non-react-statics: ^3.3.2
  htmlescape: ^1.1.1
  http-proxy: ^1.18.1
  http2-express: ^1.0.1
  inquirer: 6.5.2
  intl: ^1.2.5
  is-plain-object: ^5.0.0
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  js-yaml: ^4.1.0
  jsdom: ^20.0.3
  json5: ^2.2.3
  just-extend: ^6.2.0
  lodash.defaultsdeep: ^4.6.1
  lodash.merge: ^4.6.2
  lru-cache: ^5.1.1
  markdown-table: ^1.1.3
  mkdirp: ^1.0.4
  mock-require: ^3.0.3
  morgan: ^1.10.0
  negotiator: ^1.0.0
  next: ^14.2.24
  node-fetch: ^2.7.0
  nodemon: ^3.1.9
  nx: ^20.4.6
  nyc: ^15.1.0
  one-time: ^1.0.0
  ora: 3.4.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-intl: ~6.6.8
  react-redux: ^8.1.3
  recursive-readdir: ^2.2.3
  redux: ^4.2.1
  redux-logger: ^3.0.6
  redux-thunk: ^2.4.2
  regenerator-runtime: ^0.14.1
  replace: ^1.2.2
  rimraf: ^3.0.2
  search-insights: ^2.17.3
  semver: ^7.7.1
  serve-static: ^1.16.2
  split: ^1.0.1
  start-server-and-test: ^1.15.4
  swagger-jsdoc: ^4.3.2
  swagger-ui-express: ^4.6.3
  triple-beam: ^1.4.1
  ts-jest: ^29.2.5
  ts-node: ^10.9.2
  tsx: ^4.19.3
  typescript: ^5.7.3
  uglify-js: ^3.19.3
  vitest: ^2.1.9
  webpack: ^5.98.0
  webpack-bundle-analyzer: ^4.10.2
  webpack-inject-plugin: ^1.5.5
  whatwg-fetch: 3.6.20
  winston: ^3.17.0
  workbox-build: ^4.3.1
