/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
  modulesSidebar: [{type: 'autogenerated', dirName: 'modules'}],
  pluginsSidebar: [{type: 'autogenerated', dirName: 'plugins'}],
  presetsSidebar: [{type: 'autogenerated', dirName: 'presets'}],
  // mySidebar: ['doc1', 'doc2', 'doc3'],

  // But you can create a sidebar manually

  // tutorialSidebar: [
    // 'lifecycle-graphs',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  // ],

};

export default sidebars;
