import '@gasket/plugin-config';
import '@gasket/plugin-docs';
import '@gasket/plugin-docsify';
import '@gasket/plugin-express';
import '@gasket/plugin-https';
import '@gasket/plugin-lint';
import '@gasket/plugin-start';
import '@gasket/plugin-swagger';
import '@gasket/plugin-winston';