name: CI

on:
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_BASE_REF:refs/remotes/origin/$GITHUB_BASE_REF
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm build

    - name: Test
      run: npm test
