name: Syncpack

on:
  workflow_dispatch:
  pull_request:

# Cancel in-flight syncpack runs for the same PR
concurrency:
  group: syncpack-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  syncpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --prefer-offline

      - name: Run Syncpack
        run: pnpm run syncpack lint
